(module
  (func (export "initialize_nat") (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "create_nat") (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "set_to_zero_nat")
    (param (ref eq) (ref eq) (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "set_digit_nat")
    (param (ref eq) (ref eq) (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "incr_nat")
    (param (ref eq) (ref eq) (ref eq) (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
)
