(module
  (type $block (array (mut (ref eq))))
  (global $caml_custom_event_index (mut i32) (i32.const 0))
  (func (export "caml_runtime_events_user_register")
    (param $evname (ref eq)) (param $evtag (ref eq)) (param $evtype (ref eq))
    (result (ref eq))
    (global.set $caml_custom_event_index
      (i32.add (global.get $caml_custom_event_index) (i32.const 1)))
    (array.new_fixed $block 5 (ref.i31 (i32.const 0))
      (ref.i31 (global.get $caml_custom_event_index)) (local.get $evname)
      (local.get $evtag) (local.get $evtype))
  )
  (func (export "caml_runtime_events_user_resolve")
    (param (ref eq) (ref eq) (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_runtime_events_start")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_runtime_events_pause")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_runtime_events_resume")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_ml_runtime_events_are_active")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_runtime_events_free_cursor")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_runtime_events_read_poll")
    (param (ref eq) (ref eq) (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func (export "caml_ml_runtime_events_path")
    (param (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
)
