(module
  (type $float (struct (field $f f64)))
  (type $block (array (mut (ref eq))))
  (func $caml_gc_minor (export "caml_gc_minor")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_major (export "caml_gc_major")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_full_major (export "caml_gc_full_major")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_compaction (export "caml_gc_compaction")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_counters (export "caml_gc_counters")
    (param $x (ref eq)) (result (ref eq))
    (local $f (ref eq))
    (local.set $f (struct.new $float (f64.const 0)))
    (array.new_fixed $block 4 (ref.i31 (i32.const 0)) (local.get $f)
      (local.get $f) (local.get $f))
  )
  (func $caml_gc_stat (export "caml_gc_stat") (export "caml_gc_quick_stat")
    (param $x (ref eq)) (result (ref eq))
    (local $f (ref eq))
    (local.set $f (struct.new $float (f64.const 0)))
    (array.new_fixed $block 18 (ref.i31 (i32.const 0)) (local.get $f)
      (local.get $f) (local.get $f) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)))
  )
  (func $caml_gc_set (export "caml_gc_set")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_get (export "caml_gc_get")
    (param $x (ref eq)) (result (ref eq))
    (array.new_fixed $block 12 (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0))
      (ref.i31 (i32.const 0)) (ref.i31 (i32.const 0)))
  )
  (func $caml_gc_huge_fallback_count (export "caml_gc_huge_fallback_count")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_major_slice (export "caml_gc_major_slice")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_major_bucket (export "caml_gc_major_bucket")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_major_credit (export "caml_gc_major_credit")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_minor_free (export "caml_gc_minor_free")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_gc_minor_words (export "caml_gc_minor_words")
    (param $x (ref eq)) (result (ref eq))
    (struct.new $float (f64.const 0))
  )
  (func $caml_final_register (export "caml_final_register")
    (param $x (ref eq)) (param $x_2 (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_final_register_called_without_value
    (export "caml_final_register_called_without_value")
    (param $x (ref eq)) (param $x_2 (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_final_release (export "caml_final_release")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_memprof_start (export "caml_memprof_start")
    (param $x (ref eq)) (param $x_2 (ref eq)) (param $x_3 (ref eq))
    (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_memprof_set (export "caml_memprof_set")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_memprof_stop (export "caml_memprof_stop")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_eventlog_pause (export "caml_eventlog_pause")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
  (func $caml_eventlog_resume (export "caml_eventlog_resume")
    (param $x (ref eq)) (result (ref eq))
    (ref.i31 (i32.const 0))
  )
)
